name: CI/CD Pipeline

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install

      - name: Build library
        run: yarn lib build-only:production

      - name: Build application
        run: yarn app build-only:production

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install

      - name: Test library
        run: yarn lib test:unit

  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install

      - name: Lint library
        run: yarn lint-lib

      - name: Lint application
        run: yarn lint-app

      - name: Library type check
        run: yarn lib type-check

      - name: Build library
        run: yarn lib build-only:production

      - name: Application type check
        run: yarn app type-check

  push_to_registry_prod:
    name: Push Docker image prod

    runs-on: ubuntu-latest

    needs: [build, tests, lint-and-typecheck]

    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    environment:
      name: DockerHub_Prod
      url: https://hub.docker.com

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}
          tags: latest
          labels: latest

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  server_update_prod:
    needs: push_to_registry_prod
    name: Run prod docker container
    runs-on: ubuntu-latest

    environment:
      name: Production
      url: https://gasconsumer-ui.ru

    steps:
      - name: Connect and run script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER_LOGIN }}
          password: ${{ secrets.SERVER_USER_PASSWORD }}
          script_stop: true
          script: bash deploy_prod.sh

  push_to_registry_dev:
    name: Push Docker image dev

    runs-on: ubuntu-latest

    needs: [build, tests, lint-and-typecheck]

    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'

    environment:
      name: DockerHub_Dev
      url: https://hub.docker.com

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}
          tags: latest
          labels: latest

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  server_update_dev:
    needs: push_to_registry_dev
    name: Run dev docker container
    runs-on: ubuntu-latest

    environment:
      name: Development
      url: https://gasconsumer-ui.ru:8080

    steps:
      - name: Connect and run script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER_LOGIN }}
          password: ${{ secrets.SERVER_USER_PASSWORD }}
          script_stop: true
          script: bash deploy_dev.sh

  release:
    name: release
    runs-on: ubuntu-latest

    needs: [build, tests, lint-and-typecheck]

    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true

      - name: Automatic GitHub Release
        uses: justincy/github-action-npm-release@2.0.2
        id: release
        with:
          path: ${{ format('{0}/{1}', github.workspace, 'libs/components') }}

      - name: Publish
        if: steps.release.outputs.released == 'true'
        run: |
          yarn install
          yarn lib build-only:production
          yarn lib publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
